### ISSUE TITLE
500 - Service URL is not available for tenant ID

### ISSUE THREAD

**Issue by tinsheep** [OfficeDev/microsoft-teams-sample-meetings-token#9]
Hi - so i was getting the 
Audience validation failed. Audiences: 'api://myngrokdomain.ngrok.io/f7ff0573-b72c-4d7c-ab35-772c249ccd22'. Did not match: validationParameters.ValidAudience: 'f7ff0573-b72c-4d7c-ab35-772c249ccd22.
The readme says to put in your app id for the AzureAD:ApplicationID so i did. When i saw this didn't match i put in my application id URI instead and I got past this error. Is this documentation still accurate or am i doing something else wrong?

So not i got a valid token but now I'm running into the "Service URL is not available in tenant ID" in the MeetingService.cs GetMeetingRoleAsync. Its all in the same tenant and everything looks right to me so I'm wondering if you have some suggestions
on where to look.

Thanks!
Michael

**Comment by cristianoag** [comment]
Hi @tinsheep, that is happening because the implementation of ITenantInfoRepository included in the sample uses an in-memory store for the service URL. So the mapping is lost when the service is restarted. If you open the TokenBot.cs file you will see a comment mentioning that. Two ways to solve your issue: (1) you can send a message to the bot, the OnConversationUpdateActivityAsync handler will fire and the ServiceURL will be extracted from the message and included in the dictionary used to store the service URL. (2) you can include the ServiceURL as a configuration parameter for your solution and read it in the InMemoryTenantInfoRepository GetServiceUrl method defined on InMemoryTenantInfoRepository.cs.  Be aware that the ServiceURL can change depending on the region you're running your solution.

https://smba.trafficmanager.net/emea/  for EMEA
https://smba.trafficmanager.net/amer/  for the Americas

**Comment by tinsheep** [comment]
@cristianoag thank you so much for the reply. I was confused about the service URL but you helped me resolve it. I guess I should have been able to track this down in the code. I did the reset command for now which i didn't think i needed to do from startup and i see that it assigned the Americas address above that you noted.
